[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TatooineMesher"
dynamic = ["version"]
description = "Interpolate and/or mesh rivers from cross-sections profiles (and constraint lines)"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
authors = [
    {name = "Luc Duron", email = "l.duron@cnr.tm.fr"},
]

dependencies = [
    "jinja2",
    "matplotlib",
    "numpy",
    "pyshp>=2.0",
    "scipy",
    "shapely",
    "triangle",
]

[project.optional-dependencies]
crue10 = [
    "Crue10_tools @ git+https://github.com/CNR-Engineering/Crue10_tools.git@4.0",
]
pyteltools = [
    "PyTelTools @ git+https://github.com/CNR-Engineering/PyTelTools.git@master",
]
gdal = [
    "gdal",
]
all = [
    "TatooineMesher[crue10,pyteltools,gdal]",
]

[project.urls]
Homepage = "https://github.com/CNR-Engineering/TatooineMesher"

[tool.setuptools.packages.find]
include = ["tatooinemesher*"]
exclude = ["cli*", "tests*"]

[tool.setuptools.dynamic]
version = {attr = "tatooinemesher.VERSION"}
